import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageSelector from "@/components/Language/LanguageSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
            <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 flex flex-col">

          <header className="bg-black shadow py-4">
             <div className="container mx-auto px-4 flex justify-between items-center">
               <h1 className="text-2xl font-bold">AI Teacher</h1>
               <LanguageSelector /> 
             </div>
           </header>
          {children}
          <footer className="bg-gray-100 py-4 text-center text-gray-500 mt-auto">
            © {new Date().getFullYear()} AI Teacher
          </footer>
        </div>
      </body>
    </html>
  );
}
